/**
 * Integration Tests for generateResume.js
 * 
 * Tests PDF generation functionality end-to-end
 */

const fs = require('fs');
const path = require('path');
const { loadResume, loadTemplate, compileTemplate } = require('../scripts/generateResume');

describe('generateResume - Integration Tests', () => {
    const outputDir = path.join(__dirname, '..', '..', 'output');
    const pdfPath = path.join(outputDir, 'resume.pdf');

    beforeAll(() => {
        // Ensure output directory exists
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }
    });

    afterAll(() => {
        // Clean up test artifacts
        if (fs.existsSync(pdfPath)) {
            fs.unlinkSync(pdfPath);
        }
    });

    describe('loadResume', () => {
        it('should load resume.json without errors', () => {
            expect(() => {
                loadResume();
            }).not.toThrow();
        });

        it('should return a valid resume object', () => {
            const resume = loadResume();
            expect(resume).toBeInstanceOf(Object);
            expect(resume).toHaveProperty('name');
            expect(resume).toHaveProperty('email');
        });

        it('should have required resume fields', () => {
            const resume = loadResume();
            expect(resume).toHaveProperty('experience');
            expect(resume).toHaveProperty('education');
            expect(resume).toHaveProperty('skills');
        });
    });

    describe('loadTemplate', () => {
        it('should load resume.html template without errors', () => {
            expect(() => {
                loadTemplate();
            }).not.toThrow();
        });

        it('should return HTML string content', () => {
            const template = loadTemplate();
            expect(typeof template).toBe('string');
            expect(template.length).toBeGreaterThan(0);
        });

        it('should contain HTML structure', () => {
            const template = loadTemplate();
            expect(template).toContain('<html');
            expect(template).toContain('</html>');
        });

        it('should contain Handlebars placeholders', () => {
            const template = loadTemplate();
            expect(template).toContain('{{');
            expect(template).toContain('}}');
        });
    });

    describe('compileTemplate', () => {
        it('should compile template with resume data', () => {
            const template = loadTemplate();
            const resume = loadResume();

            expect(() => {
                compileTemplate(template, resume);
            }).not.toThrow();
        });

        it('should return HTML string with injected data', () => {
            const template = loadTemplate();
            const resume = loadResume();
            const html = compileTemplate(template, resume);

            expect(typeof html).toBe('string');
            expect(html).toContain(resume.name);
            expect(html).toContain(resume.email);
        });

        it('should have compiled Handlebars placeholders', () => {
            const template = loadTemplate();
            const resume = loadResume();
            const html = compileTemplate(template, resume);

            // Should not contain uncompiled Handlebars syntax
            expect(html).not.toMatch(/{{[\w.]+}}/);
        });

        it('should contain resume content in compiled HTML', () => {
            const template = loadTemplate();
            const resume = loadResume();
            const html = compileTemplate(template, resume);

            // Check for injected resume data
            expect(html).toContain(resume.name);
            expect(html).toContain(resume.email);
            
            // Check for sections
            if (resume.experience && resume.experience.length > 0) {
                expect(html).toContain(resume.experience[0].company);
            }
        });

        it('should include generated timestamp', () => {
            const template = loadTemplate();
            const resume = loadResume();
            const html = compileTemplate(template, resume);

            expect(html).toContain('Generated by');
        });

        it('should handle missing optional fields gracefully', () => {
            const template = loadTemplate();
            const minimalResume = {
                name: 'Test User',
                email: 'test@example.com',
                contact: { phone: '555-1234' },
                experience: [],
                education: [],
                skills: []
            };

            expect(() => {
                compileTemplate(template, minimalResume);
            }).not.toThrow();
        });
    });

    describe('PDF output requirements', () => {
        it('should create output directory if it does not exist', () => {
            const testDir = path.join(__dirname, '..', '..', 'output');
            expect(fs.existsSync(testDir)).toBe(true);
        });

        it('should have .gitignore excluding output directory', () => {
            const gitignorePath = path.join(__dirname, '..', '..', '.gitignore');
            const gitignoreContent = fs.readFileSync(gitignorePath, 'utf-8');
            expect(gitignoreContent).toContain('output/');
        });
    });

    describe('Template HTML structure', () => {
        it('should have proper CSS styling in template', () => {
            const template = loadTemplate();
            expect(template).toContain('<style>');
            expect(template).toContain('</style>');
        });

        it('should have A4 page format settings', () => {
            const template = loadTemplate();
            expect(template).toContain('210mm');
            expect(template).toContain('297mm');
        });

        it('should have proper meta tags', () => {
            const template = loadTemplate();
            expect(template).toContain('charset');
            expect(template).toContain('viewport');
        });

        it('should have structured sections for all resume parts', () => {
            const template = loadTemplate();
            
            // Check for main container
            expect(template).toContain('container');
            
            // Check for section titles
            expect(template).toContain('section-title');
            expect(template).toContain('PROFESSIONAL EXPERIENCE');
            expect(template).toContain('EDUCATION');
            expect(template).toContain('SKILLS');
        });
    });
});
